# version: '3.8'
# services:
#   spark-master:
#       build: .
#       image: cs-spark-master
#       command: bin/spark-class org.apache.spark.deploy.master.Master
#       ports:
#         - "9090:8080"
#         - "7077:7077"
#       networks:
#         - confluent
#   spark-worker:
#     build: .
#     image: cs-spark-worker
#     command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
#     depends_on:
#       - spark-master
#     environment:
#       SPARK_MODE: worker
#       SPARK_WORKER_CORES: 2
#       SPARK_WORKER_MEMORY: 1g
#       SPARK_MASTER_URL: spark://spark-master:7077
#     networks:
#       - confluent

# networks:
#   confluent:


version: '3.8'

services:
  spark-master:
    container_name: da-spark-master
    build: .
    command: ["master"]
    # entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./book_data:/opt/spark/data
      - ./apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'
    networks:
      - confluent

  spark-history-server:
    container_name: da-spark-history
    build: .
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
    networks:
      - confluent

  spark-worker:
    container_name: da-spark-worker
    build: .
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    networks:
      - confluent
volumes:
  spark-logs:

networks:
  confluent: